### ISSUE TITLE
Dedup reaction triggers

### ISSUE THREAD

**Issue by jhaye** [lf-lang/reactor-rs#25]
https://github.com/lf-lang/lingua-franca/pull/1228 contains a test called `ReadOutputOfContainedBank` for which the last reaction, that has two triggers, fires twice. It should only be called once however, since triggers should be deduplicated.

**Comment by oowekyala** [comment]
I wonder if #28 might fix this. The problem there was a merge of a reaction into the wrong level. This is the only way AFAIK that a reaction may execute twice at the same time step, since reactions at the same level are already deduplicated.
