### ISSUE TITLE
Rename to `reactor-rs`?

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/reactor-rs#5]
For all the runtime implementations so far, we've used `reactor-<file-extension>`. Should we do the same for the Rust implementation?

**Comment by jhaye** [comment]
The crate itself has a different name already, so renaming the repo shouldn't be confusing.

**Comment by cmnrd** [comment]
Hmm, interesting. The crate is called `reactor_rt`, right? I guess we should adjust this as well.

**Comment by jhaye** [comment]
We would have to touch the code generator either way, right? So I don't see why not.

**Comment by cmnrd** [comment]
I think so, yes. I am wondering how to do this transition without breaking the code generator intermittently. Do you know if the code generator runs with a specific version of reactor-rust, or if it uses always latest master?

**Comment by jhaye** [comment]
It runs with a specific version AFAIK.

**Comment by cmnrd** [comment]
I renamed the repo. reactor-rust is still valid and forwards to reactor-rs. I will update the refs to reactor-rs in LF while working on https://github.com/lf-lang/lingua-franca/issues/1291.

**Comment by oowekyala** [comment]
Sorry for not coming in sooner. This is my only quirk with the discussion:

> Hmm, interesting. The crate is called `reactor_rt`, right? I guess we should adjust this as well.

I still think it makes more sense for the crate not to be named `reactor_rs` (instead currently it's `rt` for runtime, although just `reactor` or `lf` could also be considered). Crates are a Rust specific thing anyway, so it would be like naming the `regex` crate `regex_rs`, it's just redundant. At least, this is the reason for the current name...

**Comment by cmnrd** [comment]
Good point, I think we can leave the crate as is for now. I opened #24 to keep track of the crate naming issue.
